### ISSUE TITLE
change blog title

### ISSUE THREAD

**Issue by deralation** [deralation/test-repo#1]

**Comment by eralpkaraduman** [comment]
nasıl gidiyor?

**Comment by deralation** [comment]
Blog Title has been changed and added new content

**Comment by eralpkaraduman** [comment]
I can still see the title as "Blog Title" at http://gokhanderala.com/blog.html , should be replaced to something not looking like a test text.

**Comment by deralation** [comment]
gokhanderala.com/blog.html will have changed as a "gokhanderala.com/game6.html", therefore gokhanderala.com will be main page, i've just updated content of index.html
